project/Clase/urls.py
from django.urls import path
from . import views

app_name = "Clase"

urlpatterns = [
    path('',views.home, name="home"),
    path('Cursos/agregarCurso/',views.agregarCurso, name="agregarCurso"),
    path('Cursos/agregarProfesor/',views.agregarProfesor, name="agregarProfesor"),
    path('Cursos/agregarEstudiante/',views.agregarEstudiante, name="agregarEstudiante"),
    path('Cursos/agregarComision/',views.agregarComision, name="agregarComision"),
]

project/config/config/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

project/config/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('core.urls')),
    path('Clase/',include("Clase.urls"))
    
]

project/core/urls.py
from django.urls import path
from . import views

app_name = "core"

urlpatterns = [
    path('',views.home, name="home"),
]

project/Clase/models.py
from django.db import models

class Curso(models.Model):
    nombre = models.CharField(max_length=100)
    def __str__(self) -> str:
        return self.nombre


# Create your models here.
class Estudiante(models.Model):
    nombre = models.CharField(max_length=200)
    def __str__(self) -> str:
        return self.nombre

class Profesor(models.Model):
    nombre = models.CharField(max_length=200)
    def __str__(self) -> str:
        return self.nombre
    

class Comision(models.Model):
    nombre = models.PositiveIntegerField(unique=True)
    curso = models.ForeignKey(Curso, on_delete=models.SET_NULL,null=True, blank=True)
    profesor = models.ForeignKey(Profesor, on_delete=models.SET_NULL,null=True, blank=True)
    estudiantes = models.ManyToManyField(Estudiante)
    def __str__(self) -> str:
        return str(self.nombre)
    

project/core/models.py
from django.db import models

# Create your models here.

project/Clase/forms.py
from django import forms
from . import models

class AgregarCursoForm(forms.ModelForm):
    class Meta:
        model = models.Curso
        fields = "__all__"

class AgregarEstudianteForm(forms.ModelForm):
    class Meta:
        model = models.Estudiante
        fields = "__all__"    

class AgregarProfesorForm(forms.ModelForm):
    class Meta:
        model = models.Profesor
        fields = "__all__"    

class AgregarComisionForm(forms.ModelForm):
    class Meta:
        model = models.Comision
        fields = "__all__"

class busquedaForm(forms.Form):
    query = forms.IntegerField(label='Nombre')
    

project/Clase/views.py
from django.shortcuts import render, redirect
from . import models, forms

# Create your views here.


# def home(request):
#     query = models.Comision.objects.all()
#     context = {"comisiones":query}
#     return render(request, "Clase/index.html", context)
def home(request):
    if request.method == 'POST':
        form = forms.busquedaForm(request.POST)
        if form.is_valid():
            query = form.cleaned_data['query']

            resultados = models.Comision.objects.filter(nombre__icontains=query)
            context = {
                'form': form,
                'resultados': resultados,
            }
            return render(request, 'Clase/index.html', context)
    else:
        form = forms.busquedaForm()
    
    context = {
        'form': form,
    }
    return render(request, 'Clase/index.html', context)

def agregarCurso(request):
    if request.method == "POST":
        form = forms.AgregarCursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:home")
    else:
        form = forms.AgregarCursoForm()
    return render(request, "Clase/agregarCurso.html",context={"form":form})

def agregarEstudiante(request):
    if request.method == "POST":
        form = forms.AgregarEstudianteForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:home")
    else:
        form = forms.AgregarCursoForm()
    return render(request, "Clase/agregarEstudiante.html",context={"form":form})

def agregarProfesor(request):
    if request.method == "POST":
        form = forms.AgregarProfesorForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:home")
    else:
        form = forms.AgregarCursoForm()
    return render(request, "Clase/agregarProfesor.html",context={"form":form})

def agregarComision(request):
    if request.method == "POST":
        form = forms.AgregarComisionForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("Clase:home")
    else:
        form = forms.AgregarComisionForm()
    return render(request, "Clase/agregarComision.html", context={"form": form})

project/core/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,"core/index.html")

project/Clase/templates/Clase/agregarComision.html
{% extends 'core/base.html' %}

{% block nav %}
<a class="navbar-brand" href="#!">Salon</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Clase:home' %}">Clase</a></li>
    </ul>
</div> 
{% endblock nav %}
{% block title %}
    <header class="py-5 bg-black " >
        <div class="text-center my-5">
            <h1 class="text-white display-1  ">Clase:</h1>
        </div>
    </header>
    
{% endblock title %}
{% block content %}
<section class="py-5">
    <div class="container my-6">
        <div class="row">
            <div class="col-12  ">
                <h1 class="display-6 py-5 text-center">Agregar Comision:</a></h1>
                <form class="text-center" method="post">{% csrf_token %}
                    {{form.as_p}}
                    <p>Usa ctrl + click izquierdo<br> para seleccionar multiples estudiantes</p>
                    <button type="submit">Agregar</button>
                </form>
            </div>
        </div>
    </div>
</section> 

{% endblock content %}

project/Clase/templates/Clase/agregarCurso.html
{% extends 'core/base.html' %}

{% block nav %}
<a class="navbar-brand" href="#!">Salon</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Clase:home' %}">Clase</a></li>
    </ul>
</div> 
{% endblock nav %}
{% block title %}
<header class="py-5 bg-image-full" style="background-image: url('https://source.unsplash.com/wfh8dDlNFOk/1600x900')">
    <div class="text-center my-5">
        <img class="img-fluid rounded-circle mb-4" src="https://dummyimage.com/150x150/6c757d/dee2e6.jpg" alt="..." />
        <h1 class="text-white fs-3 fw-bolder">Creacion de Cursos:</h1>
    </div>
</header>
{% endblock title %}
{% block content %}
<section class="py-5">
    <div class="container my-6">
        <div class="row">
            <div class="col-12  ">
                <h1 class="display-6 py-5 text-center">Agregar Curso:</a></h1>
                <form class="text-center" method="post">{% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Agregar</button>
                </form>
            </div>
        </div>
    </div>
</section> 

{% endblock content %}

project/Clase/templates/Clase/agregarEstudiante.html
{% extends 'core/base.html' %}

{% block nav %}
<a class="navbar-brand" href="#!">Salon</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Clase:home' %}">Clase</a></li>
    </ul>
</div> 
{% endblock nav %}
{% block title %}
    <header class="py-5 bg-black " >
        <div class="text-center my-5">
            <h1 class="text-white display-1  ">Clase:</h1>
        </div>
    </header>
    
{% endblock title %}
{% block content %}
<section class="py-5">
    <div class="container my-6">
        <div class="row">
            <div class="col-12  ">
                <h1 class="display-6 py-5 text-center">Agregar Estudiante:</a></h1>
                <form class="text-center" method="post">{% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Agregar</button>
                </form>
            </div>
        </div>
    </div>
</section> 

{% endblock content %}

project/Clase/templates/Clase/agregarProfesor.html
{% extends 'core/base.html' %}

{% block nav %}
<a class="navbar-brand" href="#!">Salon</a>
<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a></li>
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Clase:home' %}">Clase</a></li>
    </ul>
</div> 
{% endblock nav %}
{% block title %}
    <header class="py-5 bg-black " >
        <div class="text-center my-5">
            <h1 class="text-white display-1  ">Clase:</h1>
        </div>
    </header>
    
{% endblock title %}
{% block content %}
<section class="py-5">
    <div class="container my-6">
        <div class="row">
            <div class="col-12  ">
                <h1 class="display-6 py-5 text-center">Agregar Profesor:</a></h1>
                <form class="text-center" method="post">{% csrf_token %}
                    {{form.as_p}}
                    <button type="submit">Agregar</button>
                </form>
            </div>
        </div>
    </div>
</section> 

{% endblock content %}

project/Clase/templates/Clase/index.html
{% extends 'core/base.html' %}

{% block nav %}
<a class="navbar-brand" href="#!">Salon</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'core:home' %}">Home</a></li>
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'Clase:home' %}">Clase</a></li>
        </ul>
    </div> 
{% endblock nav %}

{% block title %}
    <header class="py-5 bg-black " >
        <div class="text-center my-5">
            <h1 class="text-white display-1  ">Clase:</h1>
        </div>
    </header>
    
{% endblock title %}

{% block content %}
<section class="py-5 ">
    <div class="container my-5">
        <div class="row text-center">
                <p class=" col  fs-3 p-3"><a class="link-dark link-offset-3 " href="{% url 'Clase:agregarCurso' %}">Agregar Curso </a></p>
                <p class=" col  fs-3 p-3"><a class="link-dark link-offset-3 " href="{% url 'Clase:agregarEstudiante' %}">Agregar Estudiante</a></p>
                <p class=" col  fs-3 p-3"><a class="link-dark link-offset-3 " href="{% url 'Clase:agregarProfesor' %}">Agregar Profesor</a></p>
                <p class=" col  fs-3 p-3"><a class="link-dark link-offset-3 " href="{% url 'Clase:agregarComision' %}">Agregar Comision</a></p>
        </div>
        <div class="row justify-content-center">
            <div class="col-lg-6 text-center">
                <form method="post">
                    {% csrf_token %}
                    <h1>Buscar por comision:</h2>
                    {{ form.as_p }}
                    <button type="submit">Buscar</button>
                </form> 

                {% if resultados %}
                    <div>
                        <h3>Resultado de la búsqueda:</h2>
                        
                        {% for comision in resultados %}
                            <p>{{ comision.nombre }}</p>
                            <p>{{ comision.curso }}</p>
                            <p>{{ comision.profesor }}<br></p>
                            <p class=" fs-4">Estudiantes: </p>
                            <ul class="list-group ">
                            {% for Estudiante in comision.estudiantes.all %}
                            <li class="list-group-item ">{{ Estudiante.nombre }}</li>
                            {% endfor %}
                            </ul>
                        {% endfor %}
                        
                    </div>
                {% endif %}
            </div>
        </div>
    </div>
</section> 

{% endblock content %}

project/core/templates/core/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        {% load static %}
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Salon</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'core/css/styles.css'%}" rel="stylesheet" />
    </head>
    <body>
        <!-- Responsive navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
            <div class="container">
                {% block nav %}
                {% endblock nav %}
            </div>
        </nav>
        {% block title %}
        <!-- Header - set the background image for the header in the line below-->
        {% endblock title %}
        <!-- Content section-->
        {% block content %} 
        {% endblock content %}
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src=""></script>
    </body>
</html>

project/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block nav %} 
                <a class="navbar-brand" href="#!">Salon</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                        <li class="nav-item"><a class="nav-link " aria-current="page" href="#!">Home</a></li>
                        <li class="nav-item"><a class="nav-link active" href="{% url 'Clase:home' %}">Clase</a></li>
                    </ul>
                </div> 
{% endblock nav %}
{% block content %} 

{% endblock content %}